  - name: Prettier Action
  # You may pin to the exact commit or the version.
  # uses: creyD/prettier_action@31355f8eef017f8aeba2e0bc09d8502b13dbbad1
  uses: creyD/prettier_action@v4.3
  with:
    # Commit message, will be ignored if used with same_commit
    commit_message: # optional, default is Prettified Code!
    # Extended commit message, will be ignored if used with same_commit
    commit_description: # optional, default is 
    # Update the current commit instead of creating a new one
    same_commit: # optional
    # Commit options
    commit_options: # optional
    # Git push options
    push_options: # optional
    # File pattern used for `git add`, can't be used with only_changed!
    file_pattern: # optional, default is *
    # Options for the `prettier` command
    prettier_options: "--write ." # optional, default is --write **/*.js
    # Running the script in dry mode just shows whether there are files that should be prettified or not
    dry: # optional
    # Specific version of prettier (by default just use the latest version)
    prettier_version: # optional
    # Specify a directory to cd into before installing prettier and running it
    working_directory: # optional
    # Only prettify files changed in the last commit, can't be used with file_pattern!
    only_changed: # optional
    # Install Prettier plugins, i.e. `@prettier/plugin-php @prettier/plugin-other`
    prettier_plugins: # optional, default is 
    # GitHub Token or PAT token used to authenticate against a repository
    github_token: # optional, default is ${{ github.token }}
    # Remove the node_modules folder before committing changes
    clean_node_folder: # optional, default is true
          
